### ISSUE TITLE
Print image issue

### ISSUE THREAD

**Issue by NeerajItdose** [ZebraDevs/LinkOS-Android-Samples#11]
I have a zebra zq120 and trying to print an image but it's print as string content.

```
public void printBarcode(View view) {
       ZebraPrinter  printer = ZebraPrinterFactory.getInstance(connection);
            try {
                MultiFormatWriter multiFormatWriter = new MultiFormatWriter();
                BitMatrix bitMatrix = multiFormatWriter.encode(binding.inputAddress.getText().toString(), BarcodeFormat.QR_CODE, 200, 200);
                BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
                Bitmap bitmap = barcodeEncoder.createBitmap(bitMatrix);
                binding.barcode.setImageBitmap(bitmap);
                printer.printImage(new ZebraImageAndroid(bitmap), 0, 0, 200, 200, false);
                SettingsHelper.saveBluetoothAddress(this, getMacAddressFieldText());
            } catch (WriterException | ZebraIllegalArgumentException e) {
                System.out.println("file error " + e.toString());
            } catch (ConnectionException e1) {
                System.out.println("file error " + e1.toString());
                helper.showErrorDialogOnGuiThread("Error sending file to printer");
            }
    }
```

**Comment by ssizebra** [comment]
ZQ120 is a CPCL printer, i.e. uses CPCL as the label format language. Therefore, you need to get a CPCL printer instance. Try the following. Hope this helps.

       ZebraPrinter  printer = ZebraPrinterFactory.getInstance(**CPCL**, connection);

**Comment by NeerajItdose** [comment]
> ZQ120 is a CPCL printer, i.e. uses CPCL as the label format language. Therefore, you need to get a CPCL printer instance. Try the following. Hope this helps.
> 
> ```
>    ZebraPrinter  printer = ZebraPrinterFactory.getInstance(CPCL, connection);
> ```

Not working.

**Comment by ssizebra** [comment]
I've just tried the follow code to print an image (ZebraLogo.png) stored in the Download folder on Android over Bluetooth. The printer instance is with "CPCL" for zQ120. If nothing prints in your case, make sure your image conversion function doesn't have issues.

// Always use a separate thread to deal with printers. Never use UI thread.
new Thread(new Runnable() {
    public void run() {

        Connection conn = null;
        try {
            conn = ConnectionBuilderInternal.build("98:07:2D:37:B9:0C");

            conn.open();

            printer = ZebraPrinterFactory.getInstance(CPCL, conn);

            printer.printImage(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS) + "/ZebraLogo.png", 0, 0, 200, 200, false);

        } catch (Exception e) {
            Log.v(TAG, "exception = " + e.toString());

        } finally {
            if (conn != null) {
                conn.close();
            }
        }
    }
}).start();

**Comment by NeerajItdose** [comment]
Thank. It's working.
